### ISSUE TITLE
Incompatibility with yfiles_jupyter_graphs

### ISSUE THREAD

**Issue by alonsosilvaallende** [krassowski/jupyterlab-transformers-completer#14]
The package appears to be incompatible with the package `yfiles_jupyter_graphs`.
To reproduce
```bash
pip install jupyterlab jupyterlab-transformers-completer yfiles_jupyter_graphs
```
Then on the first cell:
```python
from yfiles_jupyter_graphs import GraphWidget

w = GraphWidget()
w.show()
```
There will be an infinite "Calculating Organic layout" and it will not stop.

**Comment by krassowski** [comment]
It might be the case if `yfiles_jupyter_graphs` pulls some data from external resources. Because this extension needs access to shared array feature, it has to enable stricter security policies:

```
Cross-Origin-Opener-Policy: same-origin,
Cross-Origin-Embedder-Policy: require-corp
```

which prevents fetching of such external resources.

**Comment by alonsosilvaallende** [comment]
Thank you for your answer. That makes sense.
Thank you.
