### ISSUE TITLE
Accept completion word by word and line by line

### ISSUE THREAD

**Issue by YongcaiHuang** [krassowski/jupyterlab-transformers-completer#4]
Hi Krassowski,

I am so excited and impressed that we could have the inline completion for the Jupyterlab!!

During the trial under the Jupyterlab 4.1 pre-release, I found the code completion was smooth and fast. However, it seems that completion can only be accepted chunk by chunk (across several lines). there were so many completions. Many times, they are not 100% percent what I want, and such many completion lines can be disatractive. 

therefore, it would be great if we could accept the completion word by word and line by line, like in VScode GitHub copilot.

Best regards

**Comment by krassowski** [comment]
Thank you for the feedback @EricHUANG970823. I agree, we should have these. Since acceptance is implemented in JupyterLab itself, would you mind opening an enhancement request over at https://github.com/jupyterlab/jupyterlab/issues?

**Comment by EricHUANG970823** [comment]
Thanks. New enhancement request has been opened via her [https://github.com/jupyterlab/jupyterlab/issues/15531#issue-2041413602](url)

**Comment by krassowski** [comment]
Thank you!

**Comment by krassowski** [comment]
Closing as this is tracked in https://github.com/jupyterlab/jupyterlab/issues/15531.
